FROM scannerresearch/scanner:cpu-latest
WORKDIR /app

# Build segment kernel
COPY instance_segmentation/edges_op edges_op
RUN cd edges_op && mkdir -p build && cd build && rm -fr * && cmake .. && make
COPY instance_segmentation/instancesegm_op instancesegm_op
RUN cd instancesegm_op && mkdir -p build && cd build && rm -fr * && cmake .. && make


COPY config.toml /root/.scanner/config.toml

COPY master.py .
CMD python3 master.py
